Write a function to compute 5/0 and use try/except to catch the exceptions

In [1]:
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print(" ") 
divide(3, 0) 

Sorry ! You are dividing by zero 


Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

 

In [3]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]


sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject
                 for vb in verb 
                 for ob in obj]
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  

In [18]:
q=[1,2,3,4,5]
num=5
def matrix():
    for i in q:
        a=[i**nums for nums in range(0,num+1)]
        print(a[::-1])
matrix()

[1, 1, 1, 1, 1, 1]
[32, 16, 8, 4, 2, 1]
[243, 81, 27, 9, 3, 1]
[1024, 256, 64, 16, 4, 1]
[3125, 625, 125, 25, 5, 1]


In [14]:
import numpy as np
x = np.array([1, 2, 3,4, 5])
N = 5
def matrix():
    a=np.vander(x, N)
    print(a)
matrix()
    

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
